### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by initram** [josa42/vscode-ember-related-files#6] opened 2017-10-13 12:36 UTC
I can no longer get this extension to work.

I am using VSCode Version 1.17.1
I just get no related files when trying to use the shortcut (also tried to use the command directly).

Not sure if VSCode has changed something to break it. Let me know if there are any more information I can provide.

**Comment by enkol** [comment] 2017-10-16 13:56
I'm experiencing the same. I tried to debug the extension to find the reason and i think for my case the problem is because of Windows backslash `\` in file paths.

@initram Do you use Windows too?

I managed to get it to work again, by changing the function `activate` in `extension.ts` to convert `\`to `/`, depending on system path seperator. But i'm not sure if this is the right solution. Also i don't know why it did work beforehand (vscode <1.17). 

@josa42 Maybe it would be more suitable to fix the backslash issue within `findRelatedFiles` from `ember-find-related-files`, instead of in `vscode-ember-related-files`?

```diff
--- a/src/extension.ts
+++ b/src/extension.ts
@@ -2,7 +2,7 @@

 import * as vscode from 'vscode'
 import * as fs from 'fs'
-import { dirname, join, basename } from 'path'
+import { dirname, join, basename, sep as fileSeperator } from 'path'

 const findRelatedFiles = require('ember-find-related-files').findRelatedFiles

@@ -49,9 +49,14 @@ export function activate(context: vscode.ExtensionContext) {
       return
     }

-    const relativeFileName = vscode.workspace.asRelativePath(vscode.window.activeTextEditor.document.fileName)
+    let relativeFileName = vscode.workspace.asRelativePath(vscode.window.activeTextEditor.document.fileName);
+    let rootPath = vscode.workspace.rootPath;
+    if (fileSeperator === '\\') {
+      relativeFileName = relativeFileName.replace(/\\/g, "\/");
+      rootPath = rootPath.replace(/\\/g, "\/");
+    }

-    const items = findRelatedFiles(vscode.workspace.rootPath, relativeFileName)
+    const items = findRelatedFiles(rootPath, relativeFileName)
       .map((item) => new TypeItem(item))

     if (items.length === 0) { return; }
```

**Comment by enkol** [comment] 2017-10-16 14:33
@initram If you're on windows too and want to test if the same fix also works for you:
- close vscode
- navigate to `C:\Users\username\.vscode\extensions\josa.ember-related-files-1.1.0\out\src`
- open `extension.js`
- in function `activate` replace:
```js
        const relativeFileName = vscode.workspace.asRelativePath(vscode.window.activeTextEditor.document.fileName);
        const items = findRelatedFiles(rootPath, vscode.workspace.rootPath)
            .map((item) => new TypeItem(item));
```
with:
```js
        let relativeFileName = vscode.workspace.asRelativePath(vscode.window.activeTextEditor.document.fileName);
        let rootPath = vscode.workspace.rootPath;
        if (path_1.sep === '\\') {
            relativeFileName = relativeFileName.replace(/\\/g, "\/");
            rootPath = rootPath.replace(/\\/g, "\/");
        }
        const items = findRelatedFiles(rootPath, relativeFileName)
            .map((item) => new TypeItem(item));
```
- start vscode and try if it now works

**Comment by initram** [comment] 2017-10-16 20:39
Yes I am using windows. The fix should most likely be fixed in `ember-find-related-files` as it it just using regex with slashes on the raw paths. So it should really normalize the paths before doing that, like you have done, or come up with a better solution that does not involve parsing paths with regex.

I will try your quick fix, as I have gotten too used to this plugin to miss it.

**Comment by Alonski** [comment] 2017-11-06 07:56
I created this in a few minutes: https://marketplace.visualstudio.com/items?itemName=Alonski.ember-related-files-windows#overview
Hope it will help others coming here

**Comment by enkol** [comment] 2017-11-08 12:30
@josa42 Did you thought about adding a fix for this issue? As your extension is also listed in the [emberjs/emberjs](https://marketplace.visualstudio.com/items?itemName=emberjs.emberjs) vscode extension package, it would be nice to have it working for Windows users again, instead of having a windows specific forked extension.

If it helps, i could provide a pull request with the fix posted above in this issue ([see also fork](https://github.com/enkol/vscode-ember-related-files/commit/bcbc0fadc4c380ac09c14d0a69ad15a4cd69d505)). 

Though i think it would be better to address the issue directly within `ember-find-related-files`. I'd be willing to also provide a pull request there, once you showed interest.

**Comment by Alonski** [comment] 2017-11-08 16:53
@enkol It seems like @josa42 isn't supporting this anymore and this issue has been open for more than a month. I decided to fix this for my team and took inspiration from your code to create a separate VSCode extension. I can talk to the a few people to get the EmberJS VSCode extension to reference my extension instead of this one.
What do you think?

**Comment by josa42** [comment] 2017-11-08 16:58
@Alonski I would merge a PR if there was one.

**Closed as completed** 2017-11-08 17:24 UTC

**Comment by Alonski** [comment] 2017-11-08 20:11
Awesome @josa42! Sorry I thought I saw an open pull request. I'll go ahead and take down my extension as yours works now. Thanks a lot!
